# Generated by Django 3.1.1 on 2020-09-24 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_myprofileuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginConfirmCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_in_platform', models.CharField(default='', max_length=100)),
                ('dtime', models.IntegerField(default=30)),
                ('date_logged_in', models.DateTimeField(auto_now_add=True)),
                ('logged_user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
