# Generated by Django 3.1.1 on 2020-09-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_loginconfirmcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginconfirmcode',
            name='login_code',
            field=models.CharField(default='0123456789', max_length=30),
            preserve_default=False,
        ),
    ]
