# Generated by Django 3.1.1 on 2020-09-25 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0021_auto_20200924_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifyme',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='who_started_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
