# Generated by Django 3.1.1 on 2020-09-25 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200925_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifyme',
            name='gpost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
        migrations.AddField(
            model_name='notifyme',
            name='greport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.report'),
        ),
    ]
