# Generated by Django 3.1.1 on 2020-09-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_userscheckedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscheckedin',
            name='check_in',
            field=models.CharField(max_length=30),
        ),
    ]
