# Generated by Django 3.1.1 on 2020-09-27 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20200925_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userscheckedin',
            old_name='date_checked_in',
            new_name='date_posted',
        ),
    ]
