# Generated by Django 3.1.1 on 2020-09-27 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20200927_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscheckedin',
            name='checked_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
