# Generated by Django 3.1.1 on 2020-09-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20200927_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='why_join_Orgeon',
            field=models.CharField(max_length=100),
        ),
    ]
