# Generated by Django 3.1.1 on 2020-10-07 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0030_auto_20200928_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoConference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=False)),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('allowed_to_join', models.ManyToManyField(related_name='allowed_to_conference', to=settings.AUTH_USER_MODEL)),
                ('conference_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pending_list', models.ManyToManyField(related_name='wants_join_conference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
