# Generated by Django 3.1.1 on 2020-10-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_userscheckedin_check_in_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscheckedin',
            name='check_in_counter',
        ),
        migrations.AlterField(
            model_name='userscheckedin',
            name='checked_in_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
