# Generated by Django 3.1.1 on 2020-10-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20201008_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscheckedin',
            name='checked_in_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
