# Generated by Django 3.1.1 on 2020-10-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20201009_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscheckedin',
            name='checked_in_date',
        ),
    ]
