# Generated by Django 3.1.1 on 2020-10-09 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_remove_userscheckedin_checked_in_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscheckedin',
            name='has_checked_in',
        ),
    ]
