# Generated by Django 3.1.1 on 2020-10-09 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_remove_userscheckedin_has_checked_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscheckedin',
            name='date_checked_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
