# Generated by Django 3.1.1 on 2020-10-09 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_auto_20201009_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscheckedin',
            name='check_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
