from django.contrib import admin

from .models import (Volunteer, Events, JoinTrip, Partnership, NewsLetter, NewsUpdate, Report, Post, Comments, Gallery, ContactUs, ClientInfoProgress, NotifyMe, Reviews, UsersCheckedIn, VideoConference)

admin.site.register(Volunteer)
admin.site.register(Events)
admin.site.register(JoinTrip)
admin.site.register(Partnership)
admin.site.register(NewsLetter)
admin.site.register(NewsUpdate)
admin.site.register(Report)
admin.site.register(Post)
admin.site.register(Comments)
admin.site.register(Gallery)
admin.site.register(ContactUs)
admin.site.register(ClientInfoProgress)
admin.site.register(NotifyMe)
admin.site.register(Reviews)
admin.site.register(UsersCheckedIn)
admin.site.register(VideoConference)
